name: On comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    needs: [pr-comment]
    uses: ostatni5/gh-action-test/.github/workflows/sandbox.yml@main
    with:
      BRANCH_REF: ${{ needs.pr-comment.outputs.ref }}

  pr-comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.comment-branch.outputs.head_ref }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@d97294d304604fa98a2600a6e2f916a84b596dc7
        id: comment-branch

  
  create-status:
    permissions:
      pull-requests: write
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Add workflow result as comment on PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const workflow_name = '${{ github.workflow	}}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ needs.build.result }}' === 'success';
            const body = `${workflow_name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
